// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using Tachzukanit.Models;

namespace Tachzukanit.Migrations
{
    [DbContext(typeof(TachzukanitContext))]
    partial class TachzukanitContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Tachzukanit.Models.Apartment", b =>
                {
                    b.Property<int>("ApartmentId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("Photo");

                    b.Property<string>("RoomsNumber");

                    b.HasKey("ApartmentId");

                    b.ToTable("Apartment");
                });

            modelBuilder.Entity("Tachzukanit.Models.Malfunction", b =>
                {
                    b.Property<string>("MalfunctionId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<DateTime>("CreationDate");

                    b.Property<int?>("CurrentApartmentApartmentId")
                        .IsRequired();

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("RequestedByUserId")
                        .IsRequired();

                    b.Property<string>("Resources");

                    b.Property<int>("Status");

                    b.Property<string>("Title");

                    b.HasKey("MalfunctionId");

                    b.HasIndex("CurrentApartmentApartmentId");

                    b.HasIndex("RequestedByUserId");

                    b.ToTable("Malfunction");
                });

            modelBuilder.Entity("Tachzukanit.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("Email");

                    b.Property<string>("FacebookId");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.Property<int>("Role");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Tachzukanit.Models.Malfunction", b =>
                {
                    b.HasOne("Tachzukanit.Models.Apartment", "CurrentApartment")
                        .WithMany("malfunctions")
                        .HasForeignKey("CurrentApartmentApartmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Tachzukanit.Models.User", "RequestedBy")
                        .WithMany("malfunctions")
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
